### ISSUE TITLE
Alternatives

### ISSUE THREAD

**Issue by kachkaev** [mikesplain/nginx-proxy-pass-docker#1]
Hi @mikesplain!

Thanks for your repo - it's exactly what I've just needed. Seeing that you haven't been working on this container though, I'm wondering if you are still using it after two years. Maybe there's a mainstream alternative for doing a simple redirect like your container, which I haven't found? Would be good if you shared your thoughts.

**Comment by kachkaev** [comment]
BTW if you're still using the container, it might be worth replacing ubuntu with alpine linux as the base image – this will make the image much smaller in size! Or maybe even take [alpine nginx](https://hub.docker.com/r/_/nginx/).

**Comment by mikesplain** [comment]
You bet! I rarely use anything besides alpine anymore. I haven't kept this updated lately as most of my setups use a bigger load balancer (Kubernetes + a dynamic nginx: https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx)

**Comment by mikesplain** [comment]
This is still a really simple way, I would be down for a PR swapping for alpine if you're interested!

**Comment by kachkaev** [comment]
i've already crafted smth with alpine - will share it shortly (not near the
laptop now)

**Comment by kachkaev** [comment]
Hi @mikesplain! Thanks for a very quick reply and for willing to update the image. Here's what I ended up with:

``` dockerfile
FROM nginx:1.10.1-alpine

COPY default.conf /etc/nginx/conf.d/default.conf

ADD start.sh /start.sh
RUN chmod 700 /start.sh

EXPOSE 80

CMD ["./start.sh"]
```

`default.conf`:

``` nginx
server {
  listen 80;
  server_name docker;

  location / {
    proxy_pass              http://<proxy_pass_placeholder>;
    proxy_set_header        Host $host;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_connect_timeout   150;
    proxy_send_timeout      100;
    proxy_read_timeout      100;
    proxy_buffers           4 32k;

    client_max_body_size    0;
  }
}
```

`start.sh`:

``` bash
#!/bin/sh
/bin/sed -i "s/<proxy_pass_placeholder>/${TARGET_SERVER}/" /etc/nginx/conf.d/default.conf

nginx -g "daemon off;"
```

Feel free to change this however you want and replace the files in the image.

The only functional difference with your original image is that there no more `client_max_body_size` (I saw broken uploads so decided to remove this rule).

**Comment by mikesplain** [comment]
Awesome, well I'd like to give credit where credit is due, so if you'd like to put that into a real PR, I would be open to testing and merging it! No pressure but just figured I would offer!

Thanks!

Mike

Mike Splain
Lead DevOps Engineer
610.304.6098 (tel:610.304.6098)
mike.splain@barkly.com
www.barkly.com

**Comment by kachkaev** [comment]
Hi Mike,

If you have time, could you please consider the change from #2?

I'm about to set up a couple of redirects and feel lazy about starting a new project on docker hub for that :–)
