### ISSUE TITLE
Feature request: Support SSL

### ISSUE THREAD

**Issue by bkraul** [mikesplain/nginx-proxy-pass-docker#6]
This is a cool project! Thank you. I have been waiting for jwilder to accept cwempe's pull request that does the very same thing with nginx-proxy, but apparently jwilder is not looking into it.

One thing I would ask is the ability to support https connections. Right now, if I try this approach to redirect to an HTTPS site, I get the error:

## 400 Bad Request
The plain HTTP request was sent to HTTPS port

This means that any external server I want to connect to must have an HTTP connection available. This might not be what is wanted in some cases.

**Comment by bkraul** [comment]
Is this project even actively developed any more?

**Comment by bkraul** [comment]
y activity

**Comment by guysoft** [comment]
Was this ever solved? I see an out of date pull request at #4

**Comment by bkraul** [comment]
Nop. Developer never responded or merged requests. Assuming project is dead.

**Comment by guysoft** [comment]
Merged to this repo, which also gets built on docker hub: https://github.com/guysoft/nginx-proxy-pass-docker/

Also added support there for websockets.

**Comment by bkraul** [comment]
Thanks guysoft! Regretable not being able to do this on original repo. Will follow your fork.

**Comment by guysoft** [comment]
Will be forked unless this one wakes up

**Comment by bkraul** [comment]
I've starting routing my feat. requests to your fork 😉

**Comment by guysoft** [comment]
@bkraul fork is here : https://github.com/guysoft/nginx-proxy-pass-docker/
